### ISSUE TITLE
ModuleNotFoundError: No module named 'binary_classifier'

### ISSUE THREAD

**Issue by guyshur** [wuhaoyu3/KO-Identification#2]
While trying to use the generated embeddings for classification (python prediction.py model/mlp_pipe.pt sample.h5 sample.csv), the script imports 'binary_classifier' which isn't found. I couldn't find this module in the repository or elsewhere online. Could you please direct me to which module this is?  
Thanks

**Comment by wuhaoyu3** [comment]
The binary_classifier.py is in the cls directory, and I have already moved it to the root directory.
