### ISSUE TITLE
model.load_state_dict(torch.load(model_path)) fails on multiple GPU node in HPC

### ISSUE THREAD

**Issue by guyshur** [wuhaoyu3/KO-Identification#3]
in prediction.py, `model.load_state_dict(torch.load(model_path))
` fails for me because it tries to load the model to a second GPU than the one used earlier to get a device but that is not assigned to me.
The specific error is `raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.`.
Adding parameter to de serialize the model to the same device fixes the issue: `model.load_state_dict(torch.load(model_path, map_location=device))
`  
Recommend changing `model.load_state_dict(torch.load(model_path))
` to `model.load_state_dict(torch.load(model_path, map_location=device))
`.  
Thanks

**Comment by wuhaoyu3** [comment]
fix
